name: "[Client] Build"

on:
  workflow_dispatch:  # Enables manual trigger
  push:
    tags:
     - 'v*'
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  mac_build:
    uses: ./.github/workflows/template-build-client.yml
    with:
      os: "macos"
      targetPlatform: "StandaloneOSX"
      # add tag if build is tag triggered 
      buildName: ${{ github.ref_type == 'tag' && format('Fun Run Client {0}', github.ref_name) || 'Fun Run Client' }}
    secrets: inherit

  linux_build: 
    uses: ./.github/workflows/template-build-client.yml
    with:
      os: "ubuntu"
      targetPlatform: "StandaloneLinux64"
      # add tag if build is tag triggered 
      buildName: ${{ github.ref_type == 'tag' && format('Fun Run Client {0}', github.ref_name) || 'Fun Run Client' }}
    secrets: inherit

  windows_build:
    uses: ./.github/workflows/template-build-client.yml
    with:
      os: "windows"
      targetPlatform: "StandaloneWindows64"
      # add tag if build is tag triggered 
      buildName: ${{ github.ref_type == 'tag' && format('Fun Run Client {0}', github.ref_name) || 'Fun Run Client' }}
    secrets: inherit