name: Client Build

on:
  workflow_dispatch:  # Enables manual trigger
  push:
    tags:
     - '*'
    branches:
      - main
      - feature/add-cicd
  pull_request:
    branches:
      - main

jobs:
  mac_build:
    uses: ./.github/workflows/build-client-template.yml
    with:
      os: "macos"
      targetPlatform: "StandaloneOSX"
    secrets: inherit

  linux_build: 
    uses: ./.github/workflows/build-client-template.yml
    with:
      os: "ubuntu"
      targetPlatform: "StandaloneLinux64"
    secrets: inherit

  windows_build:
    uses: ./.github/workflows/build-client-template.yml
    with:
      os: "windows"
      targetPlatform: "StandaloneWindows64"
    secrets: inherit