name: Deploy ECS App Template

permissions:
  id-token: write

on:
  workflow_call:
    inputs:
      image_uri:
        required: true
        type: string
      git_commit_hash:
        type: string
      isApply: 
        required: true
        type: boolean
      terraform_dir:
        required: true
        type: string

      

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0

      - name: Configure AWS Credentials Plan
        if: ${{ !inputs.isApply }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_PLAN }}
          aws-region: us-east-1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        if: ${{ inputs.isApply }}
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_DEV }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ${{ inputs.terraform_dir }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ inputs.terraform_dir }}
        run: |
          terraform plan -out=tfplan \
            -var="image_uri=${{ inputs.image_uri }}" \
            -var="git_commit_hash=${{ inputs.git_commit_hash }}"

      - name: Terraform Apply
        if:  ${{ inputs.isApply }}
        working-directory: ${{ inputs.terraform_dir }}
        run: |
            terraform apply -auto-approve tfplan 

            