name: Deploy ECS App Template

permissions:
  id-token: write

on:
  workflow_call:
    inputs:
      image_uri:
        required: true
        type: string
      git_commit_hash:
        type: string
      isApply: 
        required: true
        type: boolean
      isDestroy: 
        required: true
        type: boolean
        default: false
      stage: # dev / prod
        required: true
        type: string
      # terraform state config
      terraformDir:
        required: true
        type: string
      backendBucket:
        required: true
        type: string
      backendKey:
        required: true
        type: string
      backendRegion:
        required: false
        type: string
        default: "us-east-1"
      backendDynamoTable:
        required: true
        type: string
      role_arn:
        required: true
        type: string
      role_plan_arn:
        required: true
        type: string
      desired_count:
        required: false
        type: string
        default: "" 
      

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.isApply && inputs.role_arn || inputs.role_plan_arn }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ${{ inputs.terraformDir }}
        run: |
          terraform init \
            -backend-config="bucket=${{ inputs.backendBucket }}" \
            -backend-config="key=${{ inputs.backendKey }}" \
            -backend-config="region=us-east-1" \
            -backend-config="dynamodb_table=${{ inputs.backendDynamoTable }}"

      - name: Terraform Plan
        working-directory: ${{ inputs.terraformDir }}
        run: |
          MODE_FLAG=""
          if [ "${{ inputs.isDestroy }}" == "true" ]; then
            MODE_FLAG="-destroy"
          fi

          EXTRA_ARGS=""
          if [ ! -z "${{ inputs.desired_count }}" ]; then
            EXTRA_ARGS="-var=desired_count=${{ inputs.desired_count }}"
          fi
        
          terraform plan ${MODE_FLAG} -out=tfplan \
            -var-file="${{ inputs.stage }}.tfvars" \
            -var="image_uri=${{ inputs.image_uri }}" \
            -var="git_commit_hash=${{ inputs.git_commit_hash }}" \
            ${EXTRA_ARGS}

      - name: Terraform Apply
        if:  ${{ inputs.isApply }}
        working-directory: ${{ inputs.terraformDir }}
        run: |
            terraform apply -auto-approve tfplan 

            