name: Stop Dev Server

on:
  workflow_dispatch:

jobs:
  scale_down:
    uses: ./.github/workflows/template-deploy-ecs-app.yml
    with:
      image_uri: "ignore" 
      git_commit_hash: "ignore"
      
      isApply: true
      stage: "dev"
      terraformDir: "terraform/server/deploy"
      desired_count: "0"
    secrets: 
      role_arn: ${{ secrets.AWS_ROLE_DEV }}
      role_plan_arn: ${{ secrets.AWS_ROLE_PLAN }}