name: Dev Server Build


on:
  workflow_dispatch:  # Enables manual trigger

  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  linux_build: 
    uses: ./.github/workflows/build-server-template.yml
    with:
      os: "ubuntu"
      targetPlatform: "StandaloneLinux64"
    secrets: inherit
    

  
  windows_build:
    uses: ./.github/workflows/build-server-template.yml
    with:
      os: "windows"
      targetPlatform: "StandaloneWindows64"
    secrets: inherit

  deploy_infrastructure:
    uses: ./.github/workflows/template-terraform.yml
    with:
      isApply: ${{ github.event_name == 'push' }}
      stage: "dev"
      terraformDir: "terraform/infrastructure/dev"
    secrets: inherit

  dockerize:

    # needs: linux_build
    # runs-on: ubuntu-latest
    # outputs:
    #   IMAGE_NAME_LOWER: ${{ steps.vars.outputs.IMAGE_NAME_LOWER }}
    #   TAG_NAME: ${{ steps.vars.outputs.TAG_NAME }}

    # steps:
    #   - uses: actions/checkout@v4
    #   # Download Linux artifact (only for Linux build)
    #   - name: Download Linux build artifact
    #     if: ${{ needs.linux_build.outputs.targetPlatform == 'StandaloneLinux64' }}
    #     uses: actions/download-artifact@v4
    #     with:
    #       name: Fun Run Server ${{ needs.linux_build.outputs.os }}
    #       path: ./build/StandaloneLinux64

      runs-on: ubuntu-latest
      outputs:
        IMAGE_NAME_LOWER: ${{ steps.vars.outputs.IMAGE_NAME_LOWER }}
        TAG_NAME: ${{ steps.vars.outputs.TAG_NAME }}
      steps:
      - uses: actions/checkout@v4

      # Compute variables once
      - name: Compute variables
        id: vars
        run: |
          # Lowercase repository name
          IMAGE_NAME_LOWER=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "IMAGE_NAME_LOWER=${IMAGE_NAME_LOWER}" >> $GITHUB_OUTPUT

          # Determine tag
          TAG=$(basename "$GITHUB_REF_NAME")
          echo "TAG_NAME=${TAG}" >> $GITHUB_OUTPUT
          

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ steps.vars.outputs.IMAGE_NAME_LOWER }}/fun-run-server:${{ steps.vars.outputs.TAG_NAME }} \
            -f docker/Linux/Dockerfile .

      # Login to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # push docker image
      - name: Push Docker Image
        # if: |
        #   github.event_name == 'push' && (
        #     (github.ref_type == 'branch' && github.ref_name == 'dev') ||
        #     (github.ref_type == 'tag')
        #   )
        run: |
          docker push ghcr.io/${{ steps.vars.outputs.IMAGE_NAME_LOWER}}/fun-run-server:${{ steps.vars.outputs.TAG_NAME }}

  deploy:
    needs: [ deploy_infrastructure, dockerize ]
    uses: ./.github/workflows/deploy-ecs-app-template.yml
    with:
      image_uri: ghcr.io/${{ needs.dockerize.outputs.IMAGE_NAME_LOWER }}/fun-run-server:${{ needs.dockerize.outputs.TAG_NAME }}
      isApply: ${{ github.event_name == 'push' }}
    secrets: inherit


