name: "[Dev] Deploy Server"

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  mac_build:
    uses: ./.github/workflows/template-build-server.yml
    with:
      os: "Mac"
      targetPlatform: "StandaloneOSX"
    secrets: inherit

  linux_build: 
    uses: ./.github/workflows/template-build-server.yml
    with:
      os: "Linux"
      targetPlatform: "StandaloneLinux64"
    secrets: inherit
  
  windows_build:
    uses: ./.github/workflows/template-build-server.yml
    with:
      os: "Windows"
      targetPlatform: "StandaloneWindows64"
    secrets: inherit

  deploy_infrastructure:
    uses: ./.github/workflows/template-deploy-infrastructure.yml
    with:
      isApply: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'dev' }}
      isDestroy: false
      stage: "dev"
      terraformDir: "terraform/live/infrastructure"
    secrets: 
      role_arn: ${{ secrets.AWS_ROLE_DEV }}
      role_plan_arn: ${{ secrets.AWS_ROLE_PLAN }}

  dockerize_and_push:
    needs: linux_build
    uses: ./.github/workflows/template-dockerize-and-push.yml
    with:
      artifact_name: ${{ needs.linux_build.outputs.artifact_name }}
    secrets: inherit

  deploy:
    needs: [ dockerize_and_push, deploy_infrastructure ]
    uses: ./.github/workflows/template-deploy-server.yml
    with:
      image_uri: ghcr.io/${{ needs.dockerize_and_push.outputs.REPOSITORY_LOWER_CASE }}/fun-run-server:${{ needs.dockerize_and_push.outputs.TAG_NAME }}
      git_commit_hash: ${{ needs.dockerize_and_push.outputs.COMMIT_HASH }}
      isApply: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref_name == 'dev' }}
      isDestroy: false
      stage: "dev"
      terraformDir: terraform/live/server
    secrets: 
      role_arn: ${{ secrets.AWS_ROLE_DEV }}
      role_plan_arn: ${{ secrets.AWS_ROLE_PLAN }}