name: "[Prod] Client"

on:
  workflow_dispatch:
  push:
    tags:
     - 'v*'
  pull_request:
    branches:
      - main

jobs:
  mac_build:
    uses: ./.github/workflows/template-build-client.yml
    with:
      os: "macos"
      targetPlatform: "StandaloneOSX"
      buildName: "Fun Run"
      serverAddress: "fun-run.idanyafe.com"
    secrets: inherit

  linux_build: 
    uses: ./.github/workflows/template-build-client.yml
    with:
      os: "ubuntu"
      targetPlatform: "StandaloneLinux64"
      buildName: "Fun Run"
      serverAddress: "fun-run.idanyafe.com"
    secrets: inherit

  windows_build:
    uses: ./.github/workflows/template-build-client.yml
    with:
      os: "windows"
      targetPlatform: "StandaloneWindows64"
      buildName: "Fun Run"
      serverAddress: "fun-run.idanyafe.com"
    secrets: inherit