name: Server Build


on:
  workflow_dispatch:  # Enables manual trigger
  push:
    branches:
      - main
      - feature/add-cicd
  pull_request:
    branches:
      - main

jobs:
  linux_build: 
    uses: ./.github/workflows/build-server-template.yml
    with:
      os: "ubuntu"
      targetPlatform: "StandaloneLinux64"
    

  windows_build:
    uses: ./.github/workflows/build-server-template.yml
    with:
      os: "windows"
      targetPlatform: "StandaloneWindows64"

  dockerize:
    needs: linux_build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Download Linux artifact (only for Linux build)
      - name: Download Linux build artifact
        if: ${{ needs.linux_build.outputs.targetPlatform == 'StandaloneLinux64' }}
        uses: actions/download-artifact@v4
        with:
          name: Fun Run Server ${{ needs.linux_build.outputs.os }}
          path: ./build/StandaloneLinux64

      # Build Docker image
      - name: Build Docker image
        run: |
              docker build -t ghcr.io/${{ github.repository }}/fun-run-server:latest -f docker/Linux/Dockerfile .

      # Optionally login and push to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/funrun-server:latest
