name: Use terraform apply or plan template

permissions:
  id-token: write

on:
  workflow_call:
    inputs:
      isApply:
        required: true
        type: boolean 
      isDestroy: 
        required: false
        type: boolean
        default: false
      stage:  # dev/prod
        required: true
        type: string
      terraformDir: 
        required: true
        type: string
      backendBucket:
        required: true
        type: string
      backendKey:
        required: true
        type: string
      backendRegion:
        required: false
        type: string
        default: "us-east-1"
      backendDynamoTable:
        required: true
        type: string
      role_arn:
        required: true
        type: string
      role_plan_arn:
        required: true
        type: string
        default: "dynamoDB_to_lock_terraform_state"

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.14.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ inputs.isApply && inputs.role_arn || inputs.role_plan_arn }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: ${{ inputs.terraformDir }}
        run: |
          terraform init \
            -backend-config="bucket=${{ inputs.backendBucket }}" \
            -backend-config="key=${{ inputs.backendKey }}" \
            -backend-config="region=${{ inputs.backendRegion }}" \
            -backend-config="dynamodb_table=${{ inputs.backendDynamoTable }}"

      - name: Terraform Plan
        working-directory: ${{ inputs.terraformDir }}
        run: |
          MODE_FLAG=""
          if [ "${{ inputs.isDestroy }}" == "true" ]; then
            MODE_FLAG="-destroy"
          fi

          terraform plan ${MODE_FLAG} -out=tfplan \
            -var-file="${{ inputs.stage }}.tfvars"

      - name: Terraform Apply
        if: ${{ inputs.isApply }}
        working-directory: ${{ inputs.terraformDir }}
        run: |
            terraform apply -auto-approve tfplan 