name: Terraform Deploy Prod

on:
  push:
    branches:
      - 'main'
    paths:
      - 'terraform/infrastructure/prod/**'
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/infrastructure/prod/**'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_PROD }}
          aws-region: us-east-1

      - name: Terraform Init
        working-directory: terraform/infrastructure/prod
        run: terraform init

      - name: Terraform Plan
        working-directory: terraform/infrastructure/prod
        run: terraform plan -out=tfplan

      # apply only if pull request
      - name: Terraform Apply
        if: github.event_name == 'pull_request'
        working-directory: terraform/infrastructure/prod
        run: terraform apply -auto-approve tfplan
